GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs/62b4db26e07ac5eca21d1f97

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "Greg's First Blog",
    "author": "Greg J",
    "url": "https://www.fred.com/1/",
    "likes": 0
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "author": "gjohnsx"
}

###
DELETE http://localhost:3001/api/blogs/62b5e0771b45a08b9f0ad7f2

###
PUT http://localhost:3001/api/blogs/62b23103bf01ae26ed2a749f
Content-Type: application/json

{
    "likes": 12345
}

###
PUT http://localhost:3001/api/blogs/62b23103bf01ae26ed2a749f
Content-Type: application/json

{
    "title": "changing the title seems to work..."
}