GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs/62b4db26e07ac5eca21d1f97

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdqb2hucyIsImlkIjoiNjJiN2RhYzg3ZTc4ODBmMmU1MDNiYzcyIiwiaWF0IjoxNjU2MjU2MzU4fQ.-HwtaXLzghU8EPrmlWwV1BJ8qhP8z6ZoWOrKRynRtJA

{
    "title": "gjohns token blog #61",
    "author": "gjohns",
    "url": "https://www.greg.com/token-3/",
    "likes": 0
}

###
DELETE http://localhost:3001/api/blogs/62b8796df685f0b50b8eec6a
Authorization: bearer eyJhbfciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1d2VybmFtZSI6Imdqb2hucyIsImlkIjoiNjJiN2RhYzg3ZTc4ODBmMmU1MDNiYzcyIiwiaWF0IjoxNjU2MjU2MzU4fQ.-HwtaXLzghU8EPrmlWwV1BJ8qhP8z6ZoWOrKRynRtJA

###
PUT http://localhost:3001/api/blogs/62b87779354311495e9e76f9
Content-Type: application/json

{
    "likes": 12345
}

###
PUT http://localhost:3001/api/blogs/62b23103bf01ae26ed2a749f
Content-Type: application/json

{
    "title": "changing the title seems to work..."
}