GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs/62b0c22642a1504598a64bc3

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "Backend working!",
    "author": "Greg",
    "url": "www.greg.com",
    "likes": 100
}

###
DELETE http://localhost:3001/api/blogs/62b0c22642a1504598a64bc3